default: &default
  adapter: postgresql
  encoding: unicode
  username: railsjobhub
  pool: 5

development:
  <<: *default
  host: localhost
  database: railsjobhub_development
  password: 123456

production:
  <<: *default
  host: 127.0.0.1
  database: railsjobhub_production
  password: <%= Rails.application.credentials.postgresql_password %>


test:
  <<: *default
  database: railsjobhub_test
  password: 123456
