default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: railsjobhub
  password: 123456
  pool: 5

development:
  <<: *default
  database: railsjobhub_development


test:
  <<: *default
  database: railsjobhub_test
