# Use this file to easily define all of your cron jobs.
#
# It's helpful, but not entirely necessary to understand cron before proceeding.
# http://en.wikipedia.org/wiki/Cron

# Example:
#
# set :output, "/path/to/my/cron_log.log"
#
# every 2.hours do
#   command "/usr/bin/some_great_command"
#   runner "MyModel.some_method"
#   rake "some:great:rake:task"
# end
#
# every 4.days do
#   runner "AnotherModel.prune_old_records"
# end

# Learn more: http://github.com/javan/whenever


# To write your crontab file for your jobs, execute this command:

# $ whenever --update-crontab

# Other commonly used options include:

# $ whenever --user app # set a user as which to install the crontab
# $ whenever --load-file config/my_schedule.rb # set the schedule file
# $ whenever --crontab-command 'sudo crontab' # override the crontab command

# Note: If you run the whenever --update-crontab without passing the --user attribute, cron will be generated by the current user. This mean tasks that needs other user permission will fail.
#
# You can list installed cron jobs using crontab -l.
#
# Run whenever --help for a complete list of options for selecting the schedule to use, setting variables in the schedule, etc.


every 1.day do # 1.minute 1.day 1.week 1.month 1.year is also supported
  rake "scrape:rails"
  rake "scrape:clean"
  rake "twitter:tweet"
end
